
name: PyPi Package Publisher

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    # Init. for Python version >3.x
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Lint Check
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build Check
    - name: Install builds
      run: |
        pip install --upgrade build
    - name: Build wheels
      run: python -m build

    # Installation Check
    - name: Install package
      run: python setup.py install

    # Imports Check
    - name: Import Test
      run: python -c "from irtm.toolbox import *"

    # Install Twine
    - name: Install twine
      run: |
        pip install twine
    
    # Upload to PyPi
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{secrets.PYPI_USER}}
        TWINE_PASSWORD: ${{secrets.PYPI_PASSKEY}}
      run: |
        twine upload --verbose dist/*